import { CloseIcon } from './Icons'

const SITE_NAME = 'Dial Golf'
const COMPANY_NAME = 'Dial Golf'
const CONTACT_EMAIL = 'support@dialgolf.xyz'
const EFFECTIVE_DATE = 'June 2, 2026'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h2 style={{
        fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
        fontSize: 18, fontWeight: 700, color: '#1F1D17',
        letterSpacing: '-0.02em', marginBottom: 10, marginTop: 0,
      }}>
        {title}
      </h2>
      <div style={{ fontSize: 14, color: '#4A4235', lineHeight: 1.75 }}>{children}</div>
    </div>
  )
}

const strong = { color: '#1F1D17' } as React.CSSProperties
const li = { marginBottom: 6 } as React.CSSProperties
const ul = { marginTop: 8, paddingLeft: 20 } as React.CSSProperties

function PrivacyPolicy() {
  return (
    <>
      <p style={{ fontSize: 13, color: '#6B5F4E', marginBottom: 24 }}>Effective date: {EFFECTIVE_DATE}</p>

      <p style={{ fontSize: 14, color: '#4A4235', lineHeight: 1.75, marginBottom: 24 }}>
        This Privacy Policy describes how {COMPANY_NAME} ("we," "us," or "our") collects, uses, discloses, and safeguards your information when you use the {SITE_NAME} application and related services (collectively, the "Service"). {SITE_NAME} is a golf performance tracker and social network that lets you log shots and rounds, compete in matches, share posts, message other players, and connect with friends. By creating an account or otherwise using the Service, you acknowledge that you have read and understood this Privacy Policy. If you do not agree with it, please do not use the Service.
      </p>

      <Section title="1. Information We Collect">
        <p><strong style={strong}>Account information.</strong> When you register, we collect your first name, last name, email address, chosen username, and the password you set (stored only in hashed, salted form by our authentication provider). You may optionally provide a profile photo and your country.</p>
        <p style={{ marginTop: 10 }}><strong style={strong}>Profile and golf data.</strong> Information you add to your profile, including your handicap index, home course, goals, equipment ("what's in the bag"), and the golf data you log — shots, club selections, yardages, scorecards, rounds, and practice sessions.</p>
        <p style={{ marginTop: 10 }}><strong style={strong}>Content you create.</strong> Photos and captions you post, comments you write, and any other content you upload or submit ("User Content").</p>
        <p style={{ marginTop: 10 }}><strong style={strong}>Social interactions.</strong> Your friends and friend requests, direct messages, likes, comments, post tags, reposts, match invitations, and notifications generated by these activities.</p>
        <p style={{ marginTop: 10 }}><strong style={strong}>Wallet and competition data.</strong> If you use the in-app Dial Wallet, we store your virtual balance, transaction records, and the matches and friendly wagers you participate in.</p>
        <p style={{ marginTop: 10 }}><strong style={strong}>Technical data.</strong> Standard server and device information such as IP address, browser or device type, and interactions with the Service, collected for security, debugging, and reliability.</p>
      </Section>

      <Section title="2. How We Use Your Information">
        <p>We use the information we collect to:</p>
        <ul style={ul}>
          <li style={li}>Provide, operate, personalise, and improve the Service;</li>
          <li style={li}>Authenticate your account and send transactional messages such as email verification and password resets;</li>
          <li style={li}>Power social features — display your posts, profile, comments, messages, friends, and notifications to the appropriate people;</li>
          <li style={li}>Calculate club averages, statistics, rankings, and recommendations from your data;</li>
          <li style={li}>Maintain the safety and integrity of the Service, including reviewing reported content and enforcing our Terms;</li>
          <li style={li}>Respond to your support requests; and</li>
          <li style={li}>Comply with legal obligations.</li>
        </ul>
        <p style={{ marginTop: 8 }}>We do not use your data for third-party advertising, and we do not sell your personal information.</p>
      </Section>

      <Section title="3. Information That Is Public or Shared With Other Users">
        <p>{SITE_NAME} is a social product, so some information is, by design, visible to other users:</p>
        <ul style={ul}>
          <li style={li}><strong style={strong}>Profile:</strong> your username, profile photo, country and flag, handicap, rank and points, and win/loss record may be visible to other players.</li>
          <li style={li}><strong style={strong}>Posts:</strong> photos, captions, like counts, and comments are visible to other users, who may like, comment on, repost, or report them.</li>
          <li style={li}><strong style={strong}>Direct messages:</strong> are visible to you and the recipient(s) of the conversation.</li>
          <li style={li}><strong style={strong}>Matches and friends:</strong> participants can see one another's names, scores, and related activity; your friend list may be viewable.</li>
        </ul>
        <p style={{ marginTop: 8 }}>Please be thoughtful about what you choose to post or send. We otherwise share information only with the service providers described below, when required by law or to respond to lawful requests, to protect rights and safety, or in connection with a merger, acquisition, or sale of assets (in which case we will provide notice).</p>
      </Section>

      <Section title="4. Data Storage and Security">
        <p>Your data is stored using <strong style={strong}>Supabase</strong>, a managed cloud platform built on Amazon Web Services (AWS), and images are stored in Supabase Storage. All data is transmitted over encrypted HTTPS connections.</p>
        <p style={{ marginTop: 10 }}>We enforce Row-Level Security (RLS) policies at the database level so that private data — such as your messages and account details — is accessible only to authorised accounts. While we take reasonable technical and organisational measures to protect your information, no method of transmission or storage is completely secure, and we cannot guarantee absolute security.</p>
      </Section>

      <Section title="5. Data Retention">
        <p>We retain your account, content, and activity data for as long as your account remains active. If you delete your account, we will delete or de-identify your personal data within 30 days, except where we are required or permitted to retain it for legal, security, or regulatory purposes. Content you shared with others (for example, messages you sent) may remain visible to those recipients.</p>
      </Section>

      <Section title="6. Third-Party Services">
        <p>The Service relies on the following providers, each of which processes data on our behalf:</p>
        <ul style={ul}>
          <li style={li}><strong style={strong}>Supabase</strong> — authentication, database, realtime, and file storage (supabase.com/privacy).</li>
          <li style={li}><strong style={strong}>Vercel</strong> — application hosting and content delivery (vercel.com/legal/privacy-policy).</li>
          <li style={li}><strong style={strong}>GolfCourseAPI</strong> — golf course and tee data used to populate course search. We send only your search query, not your personal data.</li>
        </ul>
        <p style={{ marginTop: 8 }}>We do not integrate advertising networks, third-party analytics platforms, or social-media tracking pixels.</p>
      </Section>

      <Section title="7. Cookies and Local Storage">
        <p>{SITE_NAME} uses a session token issued by our authentication provider to keep you signed in, and your browser's local storage to remember certain preferences. We do not use advertising or cross-site tracking cookies.</p>
      </Section>

      <Section title="8. Your Privacy Rights">
        <p>Depending on your jurisdiction (including under the GDPR and CCPA/CPRA), you may have the right to:</p>
        <ul style={ul}>
          <li style={li}>Access the personal data we hold about you;</li>
          <li style={li}>Request correction of inaccurate data;</li>
          <li style={li}>Request deletion of your account and associated data;</li>
          <li style={li}>Object to or restrict certain processing; and</li>
          <li style={li}>Request a portable copy of your data.</li>
        </ul>
        <p style={{ marginTop: 8 }}>To exercise any of these rights, contact us at <strong style={strong}>{CONTACT_EMAIL}</strong>. We will respond within the timeframe required by applicable law (generally within 30 days). We will not discriminate against you for exercising your rights.</p>
      </Section>

      <Section title="9. International Data Transfers">
        <p>We and our service providers may process and store your information in countries other than your own, including the United States. Where required, we rely on appropriate safeguards for such transfers. By using the Service, you understand your information may be transferred to and processed in these locations.</p>
      </Section>

      <Section title="10. Children's Privacy">
        <p>The Service is intended for individuals aged 18 and older. We do not knowingly collect personal information from anyone under 18. If we learn that we have collected data from a minor, we will delete it promptly. If you believe a minor has provided us information, contact <strong style={strong}>{CONTACT_EMAIL}</strong>.</p>
      </Section>

      <Section title="11. Changes to This Policy">
        <p>We may update this Privacy Policy from time to time. If we make material changes, we will notify you by email or through a prominent notice within the Service. The "Effective date" above indicates when the policy was last revised. Your continued use of the Service after changes take effect constitutes acceptance of the updated policy.</p>
      </Section>

      <Section title="12. Contact Us">
        <p>If you have questions or concerns about this Privacy Policy or our data practices, contact us at <strong style={strong}>{CONTACT_EMAIL}</strong>.</p>
      </Section>
    </>
  )
}

function TermsOfService() {
  return (
    <>
      <p style={{ fontSize: 13, color: '#6B5F4E', marginBottom: 24 }}>Effective date: {EFFECTIVE_DATE}</p>

      <p style={{ fontSize: 14, color: '#4A4235', lineHeight: 1.75, marginBottom: 24 }}>
        These Terms of Service ("Terms") form a binding agreement between you and {COMPANY_NAME} ("we," "us," or "our") and govern your access to and use of the {SITE_NAME} application and related services (the "Service"). Please read them carefully. By creating an account or using the Service, you agree to be bound by these Terms and by our Privacy Policy. If you do not agree, do not use the Service.
      </p>

      <Section title="1. Eligibility">
        <p>You must be at least 18 years old to use the Service. By creating an account, you represent and warrant that you meet this requirement and that the information you provide is accurate and complete. Where you use features involving virtual balances or wagers, you further represent that doing so is lawful in your jurisdiction.</p>
      </Section>

      <Section title="2. Account Registration and Security">
        <p>To use the Service you must create an account with a valid email address, a username, and a secure password. You are responsible for:</p>
        <ul style={ul}>
          <li style={li}>Maintaining the confidentiality of your credentials;</li>
          <li style={li}>All activity that occurs under your account; and</li>
          <li style={li}>Notifying us immediately at {CONTACT_EMAIL} of any unauthorised access.</li>
        </ul>
        <p style={{ marginTop: 8 }}>You may not share your credentials, create an account for someone else without authorisation, impersonate others, or select a username that is misleading, offensive, or infringes another's rights.</p>
      </Section>

      <Section title="3. Description of the Service">
        <p>{SITE_NAME} is a golf performance tracker and social network. It lets you log shots and rounds, track club distances and statistics, receive recommendations, record practice, compete in matches, and connect socially — including profiles, posts, comments, likes, reposts, direct messages, friends, and notifications. The Service is provided for personal, non-commercial use. Statistics and recommendations are estimates based on the data you log and do not constitute professional golf instruction.</p>
      </Section>

      <Section title="4. User Content and Licence">
        <p>You retain ownership of the content you create or upload, including photos, captions, comments, and messages ("User Content"). You represent and warrant that you own or have the necessary rights to your User Content and that it does not infringe the rights of any third party or violate any law.</p>
        <p style={{ marginTop: 10 }}>By submitting User Content, you grant {COMPANY_NAME} a worldwide, non-exclusive, royalty-free licence to host, store, reproduce, display, and distribute that content <strong style={strong}>solely as necessary to operate and provide the Service</strong> — for example, to display your posts to other users, enable reposts and comments, and deliver your messages to their recipients. This licence ends when you delete the content or your account, except for content already shared with others or retained as required by law or for backup purposes.</p>
      </Section>

      <Section title="5. Community Guidelines and Acceptable Use">
        <p>To keep {SITE_NAME} safe and welcoming, you agree not to post, send, or share content, or engage in conduct, that:</p>
        <ul style={ul}>
          <li style={li}>Is unlawful, fraudulent, deceptive, or promotes illegal activity;</li>
          <li style={li}>Harasses, bullies, threatens, or intimidates another person;</li>
          <li style={li}>Contains hate speech or attacks people based on race, ethnicity, religion, gender, sexual orientation, disability, or similar characteristics;</li>
          <li style={li}>Is sexually explicit, pornographic, or graphically violent;</li>
          <li style={li}>Infringes any intellectual-property or privacy right;</li>
          <li style={li}>Is spam, or involves bulk or automated messaging, scraping, or data harvesting;</li>
          <li style={li}>Contains malware or attempts to gain unauthorised access to the Service or other users' accounts; or</li>
          <li style={li}>Interferes with or disrupts the integrity or performance of the Service.</li>
        </ul>
        <p style={{ marginTop: 8 }}>Violations may result in content removal and suspension or permanent termination of your account.</p>
      </Section>

      <Section title="6. Content Moderation and Reporting">
        <p>You can report posts that you believe violate these Terms using the in-app reporting tools. We may, but are not obligated to, review reported content and may remove content or restrict accounts at our discretion. We are not responsible for User Content created by others, and we do not endorse any opinions expressed by users.</p>
      </Section>

      <Section title="7. Direct Messages">
        <p>The Service includes private messaging. You are responsible for the messages you send. Do not use messaging to harass others, send spam or unlawful content, or distribute another person's private information without consent. Messages are visible to participants in the conversation.</p>
      </Section>

      <Section title="8. Dial Wallet and Friendly Wagers">
        <p>The Service may include a virtual "Dial Wallet" and the ability to set friendly wagers on matches among players. Unless expressly stated otherwise in writing, balances and wagers within the Service are <strong style={strong}>virtual, for entertainment and social competition only, and have no monetary or cash value</strong>. They are not redeemable for cash, and {COMPANY_NAME} is not a bank, money transmitter, or gambling operator.</p>
        <p style={{ marginTop: 10 }}>You are solely responsible for ensuring that your use of any wallet or wagering feature complies with the laws of your jurisdiction. We may modify, limit, suspend, or remove these features at any time, including where they may be restricted or prohibited by law, and we may void balances obtained through fraud, error, or violation of these Terms.</p>
      </Section>

      <Section title="9. Course Data and Recommendations">
        <p>Course information (names, tees, pars, yardages) is sourced in part from third-party data and may be incomplete or inaccurate. Distance and club recommendations are estimates derived from your own logged data and are provided for informational purposes only. You are responsible for your own play decisions; we make no guarantee as to accuracy or fitness for any particular situation.</p>
      </Section>

      <Section title="10. Intellectual Property">
        <p>The {SITE_NAME} name, logo, design, and all software comprising the Service are owned by {COMPANY_NAME} and protected by copyright, trademark, and other laws. Except for the limited right to use the Service under these Terms, no rights are granted to you. You may not copy, modify, reverse engineer, or create derivative works from the Service without our prior written consent.</p>
      </Section>

      <Section title="11. Third-Party Services">
        <p>The Service relies on third parties including Supabase (database, auth, storage), Vercel (hosting), and GolfCourseAPI (course data). Your use of the Service may also be subject to those providers' terms. We are not responsible for third-party services and disclaim liability for their acts or omissions.</p>
      </Section>

      <Section title="12. Disclaimer of Warranties">
        <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, {COMPANY_NAME.toUpperCase()} DISCLAIMS ALL WARRANTIES, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.</p>
      </Section>

      <Section title="13. Limitation of Liability">
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, {COMPANY_NAME.toUpperCase()} AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, PROFITS, OR GOODWILL, ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY FOR ANY CLAIM SHALL NOT EXCEED THE GREATER OF THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS BEFORE THE CLAIM OR USD $10.</p>
      </Section>

      <Section title="14. Indemnification">
        <p>You agree to indemnify, defend, and hold harmless {COMPANY_NAME} and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including reasonable legal fees) arising from your use of the Service, your User Content, or your violation of these Terms or of any law or third-party right.</p>
      </Section>

      <Section title="15. Suspension and Termination">
        <p>We may suspend or terminate your account at our discretion, with or without notice, if we believe you have violated these Terms, if required by law, or if we discontinue the Service. You may terminate your account at any time by contacting {CONTACT_EMAIL}. Upon termination, your right to use the Service ceases immediately; sections that by their nature should survive (including ownership, disclaimers, limitation of liability, and indemnification) will survive.</p>
      </Section>

      <Section title="16. Changes to These Terms">
        <p>We may revise these Terms from time to time. If we make material changes, we will provide notice via email or a prominent in-app notice before they take effect. Your continued use of the Service after the effective date of revised Terms constitutes acceptance of the changes.</p>
      </Section>

      <Section title="17. Governing Law and Dispute Resolution">
        <p>These Terms are governed by the laws of the applicable jurisdiction, without regard to conflict-of-laws principles. You agree to first attempt to resolve any dispute informally by contacting us. Any dispute that cannot be resolved informally shall be subject to the exclusive jurisdiction of the competent courts of the applicable jurisdiction, unless otherwise required by law.</p>
      </Section>

      <Section title="18. Miscellaneous">
        <p>These Terms, together with the Privacy Policy, constitute the entire agreement between you and {COMPANY_NAME} regarding the Service. If any provision is found unenforceable, the remaining provisions remain in effect. Our failure to enforce any right is not a waiver of it. You may not assign these Terms without our consent; we may assign them in connection with a merger, acquisition, or sale of assets.</p>
      </Section>

      <Section title="19. Contact Us">
        <p>If you have questions about these Terms, contact us at <strong style={strong}>{CONTACT_EMAIL}</strong>.</p>
      </Section>
    </>
  )
}

interface Props {
  doc: 'privacy' | 'terms'
  onClose: () => void
}

export default function LegalModal({ doc, onClose }: Props) {
  const title = doc === 'privacy' ? 'Privacy Policy' : 'Terms of Service'

  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed', inset: 0, zIndex: 200,
        background: 'rgba(31,29,23,0.55)',
        backdropFilter: 'blur(6px)', WebkitBackdropFilter: 'blur(6px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: 16, animation: 'fadeIn 0.2s ease',
      }}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{
          width: '100%', maxWidth: 640,
          background: '#FAF6EA', borderRadius: 24,
          border: '1px solid #E0D8C5',
          boxShadow: '0 40px 80px rgba(0,0,0,0.25)',
          maxHeight: 'calc(100vh - 32px)',
          display: 'flex', flexDirection: 'column',
          animation: 'scaleIn 0.25s cubic-bezier(0.16,1,0.3,1)',
        }}
      >
        {/* Header */}
        <div style={{
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          padding: '22px 24px 18px', borderBottom: '1px solid #E0D8C5', flexShrink: 0,
        }}>
          <h1 style={{
            fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
            fontSize: 24, fontWeight: 700, color: '#1F1D17',
            letterSpacing: '-0.03em', margin: 0,
          }}>
            {title}
          </h1>
          <button
            onClick={onClose}
            style={{
              width: 36, height: 36, borderRadius: 18,
              background: '#F0EBDD', border: '1px solid #E0D8C5',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              cursor: 'pointer', transition: 'background 0.15s', flexShrink: 0,
            }}
            onMouseEnter={e => { e.currentTarget.style.background = '#E0D8C5' }}
            onMouseLeave={e => { e.currentTarget.style.background = '#F0EBDD' }}
          >
            <CloseIcon size={16} color="#1F1D17" />
          </button>
        </div>

        {/* Scrollable body */}
        <div style={{ padding: '22px 24px 32px', overflowY: 'auto', WebkitOverflowScrolling: 'touch' as React.CSSProperties['WebkitOverflowScrolling'] }}>
          {doc === 'privacy' ? <PrivacyPolicy /> : <TermsOfService />}
        </div>
      </div>
    </div>
  )
}
